
[functions.notify-task]
enabled = true
verify_jwt = false
import_map = "./functions/notify-task/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/notify-task/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/notify-task/*.html" ]

[functions.sii-sync]
enabled = true
verify_jwt = true
import_map = "./functions/sii-sync/deno.json"
entrypoint = "./functions/sii-sync/index.ts"

[functions.claude-proxy]
enabled = true
verify_jwt = true
import_map = "./functions/claude-proxy/deno.json"
entrypoint = "./functions/claude-proxy/index.ts"

[functions.drive]
enabled = true
verify_jwt = true
import_map = "./functions/drive/deno.json"
entrypoint = "./functions/drive/index.ts"

[functions.procesar-cartola]
enabled = true
verify_jwt = false
import_map = "./functions/procesar-cartola/deno.json"
entrypoint = "./functions/procesar-cartola/index.ts"
